{% set name = "discorpy" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/discorpy-{{ version }}.tar.gz
  sha256: ff2016f9527bb844e95a64b2ff0b61c9346cdac20490fa63c69fa59c625e2360
build:  
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy
    - h5py
    - pillow
    - scikit-image

test:
  imports:
    - discorpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DiamondLightSource/discorpy
  license:  Apache-2.0
  license_file: LICENSE
  summary: 'Camera calibration and correction for radial distortion and perspective distortion'
  doc_url: https://discorpy.readthedocs.io  

extra:
  recipe-maintainers:    
    - nghia-vo
