{% set name = "discorpy" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/discorpy-{{ version }}.tar.gz
  sha256: 0ee2b8e7f04efbdc214fd7954bc5aa36cd3b69cc9412473b8b66a5003f46a8e6
build:  
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy
    - h5py
    - pillow
    - scikit-image

test:
  imports:
    - discorpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DiamondLightSource/discorpy
  license:  Apache-2.0
  license_file: LICENSE
  summary: 'Camera calibration with sub-pixel accuracy'
  doc_url: https://discorpy.readthedocs.io  

extra:
  recipe-maintainers:    
    - nghia-vo
