{% set name = "discorpy" %}
{% set version = "1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/discorpy-{{ version }}.tar.gz
  sha256: ead9b7ae14b02cb133a6449116562d20433d60e05691cfa46bbbd4cafa16579b
build:  
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - scipy
    - h5py
    - pillow
    - scikit-image

test:
  imports:
    - discorpy
  source_files:
    - ./tests/
  commands:
    - python -m unittest discover -s tests -v

about:
  home: https://github.com/DiamondLightSource/discorpy
  license:  Apache-2.0
  license_file: LICENSE
  summary: 'Distortion correction with high-accuracy for lens-coupled detector systems'
  doc_url: https://discorpy.readthedocs.io  

extra:
  recipe-maintainers:
    - algotom
    - nghia-vo
